FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    git \
    zip \
    unzip \
    && docker-php-ext-install pdo_pgsql \
    && apt-get clean

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY ./init.sh /

ENV PATH "$PATH:/root/.composer/vendor/bin"

WORKDIR /var/www

RUN composer global require laravel/installer

EXPOSE 8000

CMD ["php-fpm"]

